apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: robens/poleit:latest
          volumeMounts:
            - mountPath: /var/www/html/public/images
              name: website
          envFrom:
            - secretRef:
                name: website
      volumes:
          - name: website
            persistentVolumeClaim:
              claimName: website


      