apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mariadb:11.3.2
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: database
          envFrom:
            - secretRef:
                name: database
          ports:
            - containerPort: 3306
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database

      