apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: port-backend
    - protocol: TCP
      port: 80
      targetPort: 9001
      name: port-website
  type: ClusterIP
  