apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
spec:
  ingressClassName: nginx
  rules:
    - host: website.lan
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80

